Repository Code-the-Dream-School/ee-prac-team2-front, pull requests merged in 2023-12, with the labels that each got.

#38 Added Marice to front-end readme file
  README.md
Labels: documentation

#48 fix CODEOWNERS rule
  .github/CODEOWNERS
Labels: bug, devops

#49 Make sure Husky runs the same scripts as our formatting plugins
  package.json
Labels: bug, devops

#45 Update datacontainer url
  src/components/DataContainer/DataContainer.tsx
  src/utils/index.ts
Labels: devops

#52 51 windows line endings
  .editorconfig
  .eslintrc.json
  .gitattributes
  .prettierrc.json
Labels: bug, devops

#32 Activities
  package-lock.json
  package.json
  src/App.tsx
  src/components/ActivitiesList/ActivitiesList.module.css
  src/components/ActivitiesList/ActivitiesList.tsx
  src/components/ActivitiesList/mocks.ts
  src/components/ChoosingAcitvities/ChoosingActivities.tsx
Labels: styling

#33 #27_account creation _page
  package-lock.json
  src/App.tsx
  src/components/AccountCreation/AccountCreation.tsx
  src/components/AccountCreation/AccountCreationContainer.tsx
  src/components/AuthenticatedContent/AuthenticatedContent.tsx
  src/components/ChoosingAcitvities/ChoosingActivities.tsx
Labels: component

#85 #42 create group page
  package-lock.json
  package.json
  src/App.tsx
  src/components/AccountCreation/AccountCreationContainer.tsx
  src/components/Group/CreateGroupForm.tsx
  src/components/Group/GroupCreationContainer.tsx
  src/components/Group/GroupCreationResult.tsx
  src/components/Login/Login.tsx
Labels: component

#94 Demo Fixes
  src/components/AuthenticatedContent/AuthenticatedContent.tsx
  src/components/Group/GroupCreationContainer.tsx
Labels: bug
